apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: rhel-realtime
  namespace: vm-images
spec:
  source:
    registry:
      url: "docker://quay.io/jordigilh/rhel8-rt:latest"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi