apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: rt
spec:
  nodeSelector:
    node-role.kubernetes.io/worker-rt: ""
  cpu:
    isolated: "1,3"
    reserved: "0"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size:  "1G"
      count:  4
      node:  0
  realTimeKernel:
    enabled: true
  numa:
    topologyPolicy: "best-effort"
